global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'patterdale'
    scrape_interval: 60s
    scrape_timeout: 60s

    static_configs:
      - targets: ['patterdale:7001']